version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: anagrafica-backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
      DB_FOREIGN_KEYS: "true"
      SESSION_DRIVER: file
    ports:
      - "8000:8000"

